###

GET http://localhost:3000/contactos
Authorization: Bearer 

###

GET http://localhost:3000/contactos/2
Authorization: Bearer 


###
POST http://localhost:3000/contactos
Content-Type: application/json

{
  
    "name": "Martin",
    "phone": "12345",
    "userId": 2

}

###
DELETE http://localhost:3000/contactos/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoibWVzc2lAZ21haWwuY29tIiwiaWF0IjoxNjg0NzYzNDY0LCJleHAiOjE2ODQ4NDk4NjR9.CT39mY_k2HYS5bqpA31T8Uc-OoTd4sNv0tyTtIsyxJo


###
PUT http://localhost:3000/contactos/3
Authorization: Bearer 
Content-Type: application/json

{
    "name": "Messi",
    "phone": "hdbshjbhv"
  
}
