###

GET http://localhost:3000/usuarios
Authorization: Bearer 


###

GET http://localhost:3000/usuarios/3
Authorization: Bearer 

###
#login usuario
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  
    "name": "Palermo",
    "email": "lucas@gmail.com",
    "pass": "palermo123"
    
}

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  
    "name": "Guido",
    "email": "guido@gmail.com",
    "pass": "123"
    
}

###
DELETE http://localhost:3000/usuarios/10
Authorization: Bearer 

###
PUT http://localhost:3000/usuarios/1
Authorization: Bearer 
Content-Type: application/json

{
    "name": "Fede",
    "email": "fede@gmail.com",
    "pass": "fede"
  
}
