###

GET http://localhost:3000/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoibWVzc2lAZ21haWwuY29tIiwiaWF0IjoxNjg3Nzk1NTg5LCJleHAiOjE2ODc4ODE5ODl9.XJbqoJFVN-W3Y8n1kvY5KvlDTVLN5bAvBdIi8OQhXyY

###

GET http://localhost:3000/usuarios/3
Authorization: Bearer 

###
#login usuario
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  
    "name": "Messi",
    "email": "messi@gmail.com",
    "pass": "messi123"
    
}

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  
    "name": "Juan",
    "email": "juan@gmail.com",
    "pass": "1234"
    
}

###
DELETE http://localhost:3000/usuarios/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoibWVzc2lAZ21haWwuY29tIiwiaWF0IjoxNjg0NzYzNDY0LCJleHAiOjE2ODQ4NDk4NjR9.CT39mY_k2HYS5bqpA31T8Uc-OoTd4sNv0tyTtIsyxJo

###
PUT http://localhost:3000/usuarios/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoibWVzc2lAZ21haWwuY29tIiwiaWF0IjoxNjg3Nzk1NTg5LCJleHAiOjE2ODc4ODE5ODl9.XJbqoJFVN-W3Y8n1kvY5KvlDTVLN5bAvBdIi8OQhXyY
Content-Type: application/json

{
    "name": "Guidoooo",
    "email": "guido@gmail.com",
    "pass": "ronaldo"
  
}
